# Generated by Django 4.0 on 2022-02-04 12:54

import CryptographicFields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_key',
            field=CryptographicFields.fields.CharField(max_length=300, verbose_name='api_key'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=CryptographicFields.fields.CharField(max_length=300, verbose_name='secret_key'),
        ),
    ]
