# Generated by Django 4.0 on 2022-02-04 13:03

import CryptographicFields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_customuser_api_key_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_key',
            field=CryptographicFields.fields.CharField(max_length=500, verbose_name='api_key'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=CryptographicFields.fields.CharField(max_length=500, verbose_name='secret_key'),
        ),
    ]
