# Generated by Django 4.0 on 2021-12-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qub_date',
            new_name='pub_date',
        ),
    ]
